/// Product model representing items available for sale
///
/// This class manages product information including pricing, inventory,
/// and stock management for the IntegralPOS system.
library;

import 'package:intl/intl.dart';

class Product {
  final String id;
  final String? warehouseId;
  final String? categoryId;
  final String? companyId;
  final String name;
  final String sku;
  final String? description;
  final double? price; // Prix nullable pour les produits sans prix (ex: divers)
  final int stock;
  final int? minStock;
  final int? maxStock;
  final bool isActive;
  final double taxRate;
  final String? barcode;
  final String? imageUrl;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  Product({
    required this.id,
    this.warehouseId,
    this.categoryId,
    this.companyId,
    required this.name,
    required this.sku,
    this.description,
    this.price, // Prix optionnel
    required this.stock,
    this.minStock,
    this.maxStock,
    this.isActive = true,
    this.taxRate = 0.0,
    this.barcode,
    this.imageUrl,
    this.createdAt,
    this.updatedAt,
  });

  /// Checks if product has sufficient stock for requested quantity
  bool hasStock(int qty) {
    return stock >= qty;
  }

  /// Checks if product stock is below minimum threshold
  bool isLowStock() {
    if (minStock == null) return false;
    return stock <= minStock!;
  }

  /// Returns formatted price in XOF currency
  String get formattedPrice {
    if (price == null || price == 0) {
      return 'Prix à définir';
    }
    final formatter = NumberFormat.currency(
      locale: 'fr_FR',
      symbol: 'XOF',
      decimalDigits: 0,
    );
    return formatter.format(price);
  }

  /// Vérifie si le produit a un prix défini
  bool get hasPrice => price != null && price! > 0;

  /// Converts Product to JSON map
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'warehouse_id': warehouseId,
      'category_id': categoryId,
      'company_id': companyId,
      'name': name,
      'sku': sku,
      'description': description,
      'price': price ?? 0.0, // Envoyer 0.0 si null pour compatibilité API
      'stock': stock,
      'min_stock': minStock,
      'max_stock': maxStock,
      'is_active': isActive,
      'tax_rate': taxRate,
      'barcode': barcode,
      'image_url': imageUrl,
      'created_at': createdAt?.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
    };
  }

  /// Converts Product to API JSON (only fields accepted by backend database)
  /// Database schema:
  /// - id, warehouse_id, category_id, name, sku, price, stock, is_active, timestamps
  /// - SKU is auto-generated by backend if not provided
  Map<String, dynamic> toApiJson() {
    final json = {
      'name': name,
      'price': price,
      'stock': stock,
      'is_active': isActive,
    };
    
    // Optional fields
    final categoryIdValue = categoryId;
    if (categoryIdValue != null && categoryIdValue.isNotEmpty) {
      json['category_id'] = categoryIdValue;
    }
    // SKU: soit laisser vide pour auto-génération, soit envoyer si fourni
    if (sku.isNotEmpty) {
      json['sku'] = sku;
    } else {
      // Envoyer une chaîne vide pour que le backend génère le SKU
      json['sku'] = '';
    }
    
    return json;
  }

  /// Creates Product from JSON map
  factory Product.fromJson(Map<String, dynamic> json) {
    return Product(
      id: json['id'] as String,
      warehouseId: (json['warehouse_id'] ?? json['warehouseId']) as String?,
      categoryId: (json['category_id'] ?? json['categoryId']) as String?,
      companyId: (json['company_id'] ?? json['companyId']) as String?,
      name: json['name'] as String,
      sku: json['sku'] as String,
      description: json['description'] as String?,
      price: _parseDoubleSafely(json['price']), // Peut être null
      stock: _parseIntSafely(json['stock']) ?? 0,
      minStock: _parseIntSafely(json['min_stock'] ?? json['minStock']),
      maxStock: _parseIntSafely(json['max_stock'] ?? json['maxStock']),
      isActive: (json['is_active'] ?? json['isActive']) as bool? ?? true,
      taxRate: _parseDoubleSafely(json['tax_rate'] ?? json['taxRate']) ?? 0.0,
      barcode: json['barcode'] as String?,
      imageUrl: (json['image_url'] ?? json['imageUrl']) as String?,
      createdAt: _parseDateTimeSafely(json['created_at'] ?? json['createdAt']),
      updatedAt: _parseDateTimeSafely(json['updated_at'] ?? json['updatedAt']),
    );
  }

  /// Safely parses an integer from various types
  static int? _parseIntSafely(dynamic value) {
    if (value == null) return null;
    if (value is int) return value;
    if (value is num) return value.toInt();
    if (value is String) {
      final parsed = int.tryParse(value);
      if (parsed != null) return parsed;
      // If it's not a valid number string, return null
      return null;
    }
    return null;
  }

  /// Safely parses a double from various types
  static double? _parseDoubleSafely(dynamic value) {
    if (value == null) return null;
    if (value is double) return value;
    if (value is num) return value.toDouble();
    if (value is String) {
      final parsed = double.tryParse(value);
      if (parsed != null) return parsed;
      // If it's not a valid number string, return null
      return null;
    }
    return null;
  }

  /// Safely parses a DateTime from a string
  static DateTime? _parseDateTimeSafely(dynamic value) {
    if (value == null) return null;
    if (value is DateTime) return value;
    if (value is String) {
      try {
        return DateTime.parse(value);
      } catch (e) {
        return null;
      }
    }
    return null;
  }

  /// Creates a copy of this Product with updated fields
  Product copyWith({
    String? id,
    String? warehouseId,
    String? categoryId,
    String? companyId,
    String? name,
    String? sku,
    String? description,
    double? price,
    int? stock,
    int? minStock,
    int? maxStock,
    bool? isActive,
    double? taxRate,
    String? barcode,
    String? imageUrl,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Product(
      id: id ?? this.id,
      warehouseId: warehouseId ?? this.warehouseId,
      categoryId: categoryId ?? this.categoryId,
      companyId: companyId ?? this.companyId,
      name: name ?? this.name,
      sku: sku ?? this.sku,
      description: description ?? this.description,
      price: price ?? this.price,
      stock: stock ?? this.stock,
      minStock: minStock ?? this.minStock,
      maxStock: maxStock ?? this.maxStock,
      isActive: isActive ?? this.isActive,
      taxRate: taxRate ?? this.taxRate,
      barcode: barcode ?? this.barcode,
      imageUrl: imageUrl ?? this.imageUrl,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() {
    return 'Product(id: $id, name: $name, sku: $sku, price: $price, stock: $stock)';
  }
}
